name: awfarly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_icons_null_safety: ^1.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get: 4.6.5
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  qr_code_scanner: ^1.0.1
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#3F9DDE"
  adaptive_icon_foreground: "assets/app_logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
